### PR TITLE
Fix test suite after Cthulhu.jl update.

### PR DESCRIPTION
**Pull request by maleadt**
This was changed in https://github.com/JuliaDebug/Cthulhu.jl/pull/356

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]

**Comment by vchuravy** [comment]
cc: @timholy for future bumps.

**Comment by timholy** [comment]
Thanks. Hopefully doesn't count as a breaking change since it's in a test module. But nice to know, thanks for CCing me.

**Review by timholy — APPROVED** [review]

**Comment by maleadt** [comment]
> Hopefully doesn't count as a breaking change since it's in a test module.

Yeah no worries.

The hang does seem reproducible though, on 1.9-rc1 the call to `cread(out)` hangs. @vchuravy mind taking a look?

**Comment by timholy** [comment]
Come to think of it, you probably need to pass `annotate_source=false` as a kwarg to `GPUCompiler.code_typed`.

**Comment by timholy** [comment]
You may also want to make Cthulhu 2.8 the minimum version in the `[compat]` because that's the first version that supports this kwarg.

**Comment by timholy** [comment]
Glad to see that fixed it!

**Comment by maleadt** [comment]
Thanks!

**Pull request merged**
