### PR TITLE
Return undefined globals from compile()

### PR DESCRIPTION
**Pull request by jpsamaroo**
Also adds tests for `compile()` output

### CODE REVIEW

**Comment by jpsamaroo** [comment]
I'll also need the size of the global (for external initialization), commit for that coming up momentarily

**Comment by jpsamaroo** [comment]
Actually, I don't see an obvious way to get the byte size of an LLVM type. @maleadt should I just return the LLVM type for the backends to inspect? Or should I include a utility function here to calculate the size of the type?

**Comment by maleadt** [comment]
> @maleadt should I just return the LLVM type for the backends to inspect?

That seems fine, same with the functions, but I wonder if they are still valid once the module gets destroyed by emitting machine code (if it does, not entirely sure about that).

**Comment by jpsamaroo** [comment]
> That seems fine, same with the functions, but I wonder if they are still valid once the module gets destroyed by emitting machine code (if it does, not entirely sure about that).

:+1: I'll get AMDGPUnative's global stuff working with this PR and let you know if anything breaks.

Should I also propagate `undefined_gbls` to function that take `undefined_fns` (such as `link_libraries!`)?

**Comment by maleadt** [comment]
> Should I also propagate `undefined_gbls` to function that take `undefined_fns` (such as `link_libraries!`)?

That sounds reasonable. Maybe make it a named tuple then, for extensibility.

**Comment by jpsamaroo** [comment]
NamedTuples are pretty awkward to specify such that `invoke` won't complain about method ambiguities, so I'll leave out passing `undefined_gbls` to `link_libraries!` until someone needs it.

**Comment by jpsamaroo** [comment]
AMDGPUnative tests for https://github.com/JuliaGPU/AMDGPUnative.jl/pull/63 are now passing with the latest changes!

**Pull request merged**
