### PR TITLE
Runtime improvements for 1.5

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
Thoughts on whether `code_native`, an other reflection stuff, should error when it contains invalid things (undefined methods, etc)? If not, which seems reasonable, should the downstream package be responsible for calling `validate_ir`?

**Comment by jpsamaroo** [comment]
My preference is to not throw errors from reflection utils, since they're often used (by me) to debug codegen/function issues. Can IR validation just be a flag to `compile()`?

**Comment by jpsamaroo** [comment]
Oh I see, IR could be invalid at different points in the pipeline without breaking codegen. Yes, I think having the downstream packages call `validate_ir` at their preferred location is a good idea.

**Comment by maleadt** [comment]
> Can IR validation just be a flag to `compile()`?

 Yeah, that seemed simpler. Introduced such a flag, enabled by default but disabled by reflection. The flag is not documented by reflection utils, but I added a test helper that simulates execution and performs validation.

**Comment by maleadt** [comment]
CI failure is CUDA.

**Pull request merged**
