### PR TITLE
Move to Julia 1.6

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Review by vchuravy — COMMENTED** [review]
This is looking really nice!

**Comment by maleadt** [comment]
It does! Kudos to @Keno for the nice API. I also pushed the contents of this PR to https://github.com/Keno/Compiler3.jl/tree/master/dependents/GPUCompiler where it's easier to iterate on the design.

What do you think about backwards compatibility, OK to just drop? It's tempting, especially with 1.6 being the new LTS.

**Comment by jpsamaroo** [comment]
I've been playing around with the `gpu_ci_cache_lookup` function a bit, and I'm trying to get it so that I can consistently replace one `MethodInstance` with another (say, `Base.sin` with a custom GPU implementation). Unless I set `@noinline` or `OptimizationParams(;inlining=false)`, `gpu_ci_cache_lookup` doesn't necessarily get called with the `MethodInstance` that I want to replace. Is there a better place to do MI replacement that will always be called, even if the method is inlineable?

**Comment by maleadt** [comment]
cc @Keno

**Comment by maleadt** [comment]
@jpsamaroo Try in the `Core.Compiler.get(wvc::WorldView{GPUCodeCache}, mi::MethodInstance, default)` method instead, that's how inference queries the cache. `gpu_ci_cache_lookup` is only used by codegen.

**Comment by maleadt** [comment]
One curious issue on 1.6: `invokes` disappear with our compiler:

```
julia> @noinline nospecialize_child(@nospecialize(i)) = i
nospecialize_child (generic function with 1 method)

julia> kernel(a, b) = (unsafe_store!(b, nospecialize_child(a)); return)
kernel (generic function with 1 method)

julia> code_llvm(kernel, Tuple{Int,Ptr{Int}})
;  @ REPL[13]:1 within `kernel'
define void @julia_kernel_1891(i64 %0, i64 %1) {
top:
  %2 = alloca {}*, align 8
  %gcframe2 = alloca [3 x {}*], align 16
  %gcframe2.sub = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 0
  %3 = bitcast [3 x {}*]* %gcframe2 to i8*
  call void @llvm.memset.p0i8.i32(i8* nonnull align 16 dereferenceable(24) %3, i8 0, i32 24, i1 false)
  %thread_ptr = call i8* asm "movq %fs:0, $0", "=r"() #4
  %ptls_i8 = getelementptr i8, i8* %thread_ptr, i64 -32768
  %4 = bitcast [3 x {}*]* %gcframe2 to i64*
  store i64 4, i64* %4, align 16
  %5 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 1
  %6 = bitcast i8* %ptls_i8 to i64*
  %7 = load i64, i64* %6, align 8
  %8 = bitcast {}** %5 to i64*
  store i64 %7, i64* %8, align 8
  %9 = bitcast i8* %ptls_i8 to {}***
  store {}** %gcframe2.sub, {}*** %9, align 8
  %10 = call nonnull {}* @jl_box_int64(i64 signext %0)
  %11 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 2
  store {}* %10, {}** %11, align 16
  store {}* %10, {}** %2, align 8
  %12 = call nonnull {}* @jl_invoke({}* inttoptr (i64 140658151008448 to {}*), {}** nonnull %2, i32 1, {}* inttoptr (i64 140658136239888 to {}*))
; ┌ @ pointer.jl:118 within `unsafe_store!' @ pointer.jl:118
   %13 = inttoptr i64 %1 to i64*
   %14 = bitcast {}* %12 to i64*
   %15 = load i64, i64* %14, align 8
   store i64 %15, i64* %13, align 1
   %16 = load i64, i64* %8, align 8
   store i64 %16, i64* %6, align 8
; └
  ret void
}

julia> native_code_llvm(kernel, Tuple{Int,Ptr{Int}})
;  @ REPL[13]:1 within `kernel'
define dso_local void @julia_kernel_1936(i64 %0, i64 %1) local_unnamed_addr {
top:
  %2 = call fastcc nonnull {}* @jl_box_int64(i64 signext %0)
  %3 = call fastcc nonnull {}* @julia_nospecialize_child_1939({}* readonly %2)
; ┌ @ pointer.jl:118 within `unsafe_store!' @ pointer.jl:118
   %4 = inttoptr i64 %1 to i64*
   %5 = bitcast {}* %3 to i64*
   %6 = load i64, i64* %5, align 8
   store i64 %6, i64* %4, align 1
; └
  ret void
}
```

**Comment by maleadt** [comment]
More debugging, looks like we're 'caching too much' resulting in `emit_invoke` emitting different code:

```
@noinline child(@nospecialize(i)) = i
kernel(a) = (child(a); return)

f = kernel
t = Tuple{Int}
world = typemax(UInt)


using InteractiveUtils

meth = which(f, t)
t = Base.to_tuple_type(t)
tt = Base.signature_type(f, t)
(ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), tt, meth.sig)
meth = Base.func_for_method_checked(meth, ti, env)
mi = ccall(:jl_specializations_get_linfo, Ref{Core.MethodInstance}, (Any, Any, Any, UInt), meth, ti, env, world)

InteractiveUtils.print_llvm(stdout, InteractiveUtils._dump_function_linfo_llvm(mi, world, false, true, false, true, :none, Base.CodegenParams()))

println("CPU CI cache for $f:")
if isdefined(mi, :cache)
    local ci = mi.cache
    while true
        println("- $(ci)")
        isdefined(ci, :next) || break
        ci = ci.next
    end
end
println()

let f = child, t = Tuple{Int}
    meth = which(f, t)
    t = Base.to_tuple_type(t)
    tt = Base.signature_type(f, t)
    (ti, env) = ccall(:jl_type_intersection_with_env, Any, (Any, Any), tt, meth.sig)
    meth = Base.func_for_method_checked(meth, ti, env)
    mi = ccall(:jl_specializations_get_linfo, Ref{Core.MethodInstance}, (Any, Any, Any, UInt), meth, ti, env, world)

    println("CPU CI cache for $f:")
    if isdefined(mi, :cache)
        ci = mi.cache
        while true
            println("- $(ci)")
            isdefined(ci, :next) || break
            ci = ci.next
        end
    end
    println()
end


println("#"^80)
println()


using GPUCompiler, LLVM

module TestRuntime
    # dummy methods
    signal_exception() = return
    malloc(sz) = C_NULL
    report_oom(sz) = return
    report_exception(ex) = return
    report_exception_name(ex) = return
    report_exception_frame(idx, func, file, line) = return

    # for validation
    sin(x) = Base.sin(x)
end

struct TestCompilerParams <: AbstractCompilerParams end
GPUCompiler.runtime_module(::CompilerJob{<:Any,TestCompilerParams}) = TestRuntime

source = FunctionSpec(f)
target = NativeCompilerTarget()
params = TestCompilerParams()
job = CompilerJob(target, source, params)
mod, entry = GPUCompiler.irgen(job, mi, world)
str = ccall(:jl_dump_function_ir, Ref{String},
            (LLVM.API.LLVMValueRef, Bool, Bool, Ptr{UInt8}),
            entry, false, false, :none)

InteractiveUtils.print_llvm(stdout, str)

println("GPU CI cache contains $(length(GPUCompiler.GPU_CI_CACHE.dict)) entries:")
for mi in keys(GPUCompiler.GPU_CI_CACHE.dict)
    println(" - $mi")
end
```

```
define void @julia_kernel_17(i64 %0) {
top:
  %1 = alloca {}*, align 8
  %gcframe2 = alloca [3 x {}*], align 16
  %gcframe2.sub = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 0
  %2 = bitcast [3 x {}*]* %gcframe2 to i8*
  call void @llvm.memset.p0i8.i32(i8* nonnull align 16 dereferenceable(24) %2, i8 0, i32 24, i1 false)
  %thread_ptr = call i8* asm "movq %fs:0, $0", "=r"() #4
  %ptls_i8 = getelementptr i8, i8* %thread_ptr, i64 -32768
  %3 = bitcast [3 x {}*]* %gcframe2 to i64*
  store i64 4, i64* %3, align 16
  %4 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 1
  %5 = bitcast i8* %ptls_i8 to i64*
  %6 = load i64, i64* %5, align 8
  %7 = bitcast {}** %4 to i64*
  store i64 %6, i64* %7, align 8
  %8 = bitcast i8* %ptls_i8 to {}***
  store {}** %gcframe2.sub, {}*** %8, align 8
  %9 = call nonnull {}* @jl_box_int64(i64 signext %0)
  %10 = getelementptr inbounds [3 x {}*], [3 x {}*]* %gcframe2, i64 0, i64 2
  store {}* %9, {}** %10, align 16
  store {}* %9, {}** %1, align 8
  %11 = call nonnull {}* @jl_invoke({}* inttoptr (i64 140366468759568 to {}*), {}** nonnull %1, i32 1, {}* inttoptr (i64 140366472380304 to {}*))
  %12 = load i64, i64* %7, align 8
  store i64 %12, i64* %5, align 8
  ret void
}
CPU CI cache for kernel:
- Core.CodeInstance(MethodInstance for kernel(::Int64), #undef, 0x00000000000072fa, 0xffffffffffffffff, Nothing, nothing, UInt8[0x0c, 0x02, 0x00, 0x00, 0x00, 0x00, 0x08, 0x16, 0x88, 0xc1, 0xe6, 0x09, 0x03, 0x40, 0x11, 0x03, 0x1e, 0x11, 0x00, 0x38, 0xc1, 0x37, 0x3d, 0x16, 0x88, 0xc1, 0xe6, 0x3e, 0x3e, 0x16, 0x01, 0xc1, 0xf2, 0x00, 0x00, 0x3d, 0x16, 0x88, 0xc1, 0x27, 0x00, 0x2f, 0x2f, 0x23, 0x11, 0x01, 0x11, 0x02, 0xc1, 0xbf, 0x2f, 0x23, 0x11, 0x01, 0x11, 0x02, 0xc1, 0xbf, 0x3d, 0x01, 0x02], false, false, Ptr{Nothing} @0x0000000000000000, Ptr{Nothing} @0x0000000000000000)

CPU CI cache for child:
- Core.CodeInstance(MethodInstance for child(::Int64), #undef, 0x0000000000000001, 0xffffffffffffffff, Int64, #undef, nothing, false, false, Ptr{Nothing} @0x0000000000000000, Ptr{Nothing} @0x0000000000000000)

################################################################################

define dso_local void @_Z16julia_kernel_414(i64 %0) !dbg !6 {
top:
  %1 = call {}*** @julia.ptls_states()
  %2 = bitcast {}*** %1 to {} addrspace(10)**
  %3 = getelementptr inbounds {} addrspace(10)*, {} addrspace(10)** %2, i64 4
  %4 = bitcast {} addrspace(10)** %3 to i64**
  %5 = load i64*, i64** %4, align 8, !tbaa !8, !invariant.load !4
  %6 = call nonnull {} addrspace(10)* @jl_box_int64(i64 signext %0), !dbg !12
  %7 = call nonnull {} addrspace(10)* @julia_child_417({} addrspace(10)* readonly %6), !dbg !12
  ret void, !dbg !12
}
GPU CI cache contains 3 entries:
 - MethodInstance for child(::Int64)
 - MethodInstance for kernel(::Int64)
 - MethodInstance for child(::Any)
```

During `emit_invoke`, the cache is queried for `child(::Any)`, which misses the Base CI cache, but hits the GPU one.

**Comment by maleadt** [comment]
Well, that was stupid: our cache lookup called inference, so obviously the lookup from `emit_invoke` was never going to return `nothing`. Made it idempotent instead.

Passes all tests now :tada: except for SPIR-V, which is awaiting new builds of libraries.

**Comment by jpsamaroo** [comment]
Any idea why AMDGPU reverse CI would be segfaulting in LLVM?

**Comment by maleadt** [comment]
Probably a failed assertion somewhere?

**Comment by maleadt** [comment]
Same segfault with CUDA.jl.

**Comment by maleadt** [comment]
Starting to get somewhere... Let's try and keep up with Base a little better next time though.

**Comment by maleadt** [comment]
oneAPI.jl and CUDA.jl pass all tests, except for the method redefinition ones which I'll look at next week. @vchuravy, what's the status of https://github.com/JuliaLang/julia/pull/38370, is that sufficient of a fix?

**Comment by vchuravy** [comment]
> is that sufficient of a fix?

I think so! You will want to use this invalidate method https://github.com/vchuravy/KernelCompiler.jl/blob/0b91754e6857a59fb1025837305bba691146b991/src/codecache.jl#L68 and set it as a callback when entering into your cache https://github.com/vchuravy/KernelCompiler.jl/blob/0b91754e6857a59fb1025837305bba691146b991/src/codecache.jl#L23

**Comment by maleadt** [comment]
@jpsamaroo About the AMDGPU failure, it's likely you're caching values from a destroyed LLVM context somewhere. That's invalid now, as we use a new context for every compilation. Some examples:
- https://github.com/JuliaGPU/GPUCompiler.jl/pull/69/commits/3fd478eea926639361f91e28840bd84e6f64a2a0
- https://github.com/JuliaGPU/GPUCompiler.jl/pull/69/commits/e87ebd021eea21911511819be7aff576b1ac6c96
- https://github.com/JuliaGPU/GPUCompiler.jl/pull/69/commits/1f3a3110fc7eb3a39c7506f46665603daaffba99

So this is the likely culprit: https://github.com/JuliaGPU/AMDGPU.jl/blob/4ca2bcced2eb8a8cf65bbd135c93cda81ae008aa/src/device/runtime.jl#L78

**Comment by jpsamaroo** [comment]
Oh I see, I'm creating a new context whereas, like CUDA.jl, I should be using the context for the module being compiled. Thanks for pointing this out, I'll get this change on a 1.6 branch for testing when I get some time :slightly_smiling_face:

**Comment by jpsamaroo** [comment]
Actually, something I don't understand about runtime library compilation in CUDA and GPUCompiler: isn't it bad that the context is taken from the currently-compiled module, but then the loaded IR is cached and reused for later compiles (where the context is different)? Or does it not matter when linking?

**Comment by maleadt** [comment]
> the loaded IR is cached and reused

Yeah, you shouldn't cache it. GPUCompiler and CUDA.jl now re-parse the runtime and device libraries for each compilation again (to get it in the new, temporary context).

**Comment by jpsamaroo** [comment]
Ahh I see that in GPUCompiler now. But I still see this in CUDA:
https://github.com/JuliaGPU/CUDA.jl/blob/b1d2ac0cd35ccc4a9bab118864a1eadadf7c8aef/src/device/runtime.jl#L68-L76 

Won't that cache the context across compiles?

**Comment by jpsamaroo** [comment]
Oh nevermind, you removed that in your backports branch!

**Comment by maleadt** [comment]
Yeah, I only noticed it was still in CUDA.jl after mentioning it here :-) Had only been fixing things that caused segfaults, so it may not be the cause for yours, but it should be fixed regardless.

**Pull request merged**
