### PR TITLE
Remove Hack

### PR DESCRIPTION
**Pull request by collinwarner**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Waiting on https://github.com/JuliaLang/julia/pull/45544

**Comment by maleadt** [comment]
This'll still be required on older versions, right?

**Comment by jpsamaroo** [comment]
Once https://github.com/JuliaLang/julia/pull/45900 makes it to nightlies, this should be ready to go.

**Review by maleadt — APPROVED** [review]
LGTM.

Our Julia nightly CI here compiles Julia, so you don't have to wait for nightlies to arrive. There look to be some CI failures though.

**Comment by maleadt** [comment]
The output is a but mangled, but it looks like no GCN failures on master?
I take it you verified with AMDGPU.jl (which seemed to have disappeared from Buildkite)?

**Comment by jpsamaroo** [comment]
Yeah, I've been running this branch with AMDGPU's `jps/simple-execution` branch (recently merged to master) to validate that things work (which they do). I've also used it with Julia 1.7 with great success.

**Pull request merged**
