### PR TITLE
Correct inlinealloc

### PR DESCRIPTION
**Pull request by wsmoses**

### CODE REVIEW

**Comment by maleadt** [comment]
Thanks! I take it you want this backported to a version that doesn't require LLVM 6?

**Comment by wsmoses** [comment]
Yeah

**Comment by wsmoses** [comment]
I've also failed to actually make a test of this, but it does fix the bug we saw (see below):
```

julia> using ElectrochemicalKinetics
using GPUCompiler

julia> using GPUCompiler

# with the fix above
julia> GPUCompiler.is_inlinealloc(MarcusHushChidseyDOS{Float64})
false

```

**Comment by wsmoses** [comment]
@maleadt could we also get a version tag for the LLVM6 compatible branch as well?

**Pull request merged**
