### PR TITLE
Use LLVM's byval instead of rewriting kernels.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@jpsamaroo this triggers a bunch of address space-related issues with the GCN back-end :slightly_frowning_face:

**Comment by vchuravy** [comment]
No those are new https://github.com/llvm/llvm-project/blob/d359f2096850c68b708bc25a7baca4282945949f/llvm/lib/Target/AMDGPU/AMDGPUAliasAnalysis.cpp#L91-L100

By rewriting the kernel we have sofar tricked out the AA for AMDGPU.

**Comment by maleadt** [comment]
Ah, this only used to fail when testing AMDGPUnative, not during GPUCompiler's GCN tests (maybe codegen tests covering the same functionality should be put here?), and AMD CI is down...

**Comment by jpsamaroo** [comment]
AMDGPU CI should be back up. The issues with "pointer address space out of range" are due to Julia's optimization pipeline running the verifier at the beginning on debug builds, which #30 should hopefully fix for GCN.

**Comment by maleadt** [comment]
Turns out there's a problem with this on Julia 1.4: NVPTX lowers `byval` by creating an alloca in the stack AS, which conflicts when passing a pointer in another address space: https://github.com/llvm-mirror/llvm/blob/2c4ca6832fa6b306ee6a7010bfb80a3f2596f824/lib/Target/NVPTX/NVPTXLowerArgs.cpp#L141-L168
Not a problem on 1.5, where we strip address spaces.

**Pull request merged**
