### PR TITLE
Switch to PrecompileTools.jl.

### PR DESCRIPTION
**Pull request by maleadt**
Testing `examples/kernel.jl` without a precompile workload at all:

```
❯ hyperfine -w 1 " julia --project examples/kernel.jl"
Benchmark 1:  julia --project examples/kernel.jl
  Time (mean ± σ):      8.131 s ±  0.241 s    [User: 8.139 s, System: 1.156 s]
  Range (min … max):    7.873 s …  8.375 s    10 runs
```

Current master:

```
Benchmark 1:  julia --project examples/kernel.jl
  Time (mean ± σ):      7.732 s ±  0.085 s    [User: 7.723 s, System: 1.173 s]
  Range (min … max):    7.560 s …  7.818 s    10 runs
```

Before https://github.com/JuliaGPU/GPUCompiler.jl/pull/600:

```
Benchmark 1:  julia --project examples/kernel.jl
  Time (mean ± σ):      1.782 s ±  0.022 s    [User: 1.825 s, System: 1.130 s]
  Range (min … max):    1.744 s …  1.815 s    10 runs
```

This PR:

```
Benchmark 1:  julia --project examples/kernel.jl
  Time (mean ± σ):     991.3 ms ±  14.8 ms    [User: 1045.8 ms, System: 1120.8 ms]
  Range (min … max):   968.7 ms … 1013.1 ms    10 runs
```

So still an improvement. Probably doesn't matter too much for downstream users, as the whole `@nospecialize(job::CompilerJob)` doesn't really work and I think we end up respecializing the GPUCompiler code anyway (i.e., downstream packages require their own precompile workload).

### CODE REVIEW

**Comment by maleadt** [comment]
@vchuravy GPU methods leaking into the package image on Windows/1.11?

```
lld: error: undefined symbol: gpu_malloc
>>> referenced by D:\a\GPUCompiler.jl\GPUCompiler.jl\src\runtime.jl:88
>>>               jl_B252.tmp(text#0.o):(julia_box_uint8_16861)
>>> referenced by D:\a\GPUCompiler.jl\GPUCompiler.jl\src\runtime.jl:88
>>>               jl_B252.tmp(text#0.o):(julia_box_int8_16844)
>>> referenced by D:\a\GPUCompiler.jl\GPUCompiler.jl\src\runtime.jl:88
>>>               jl_B252.tmp(text#0.o):(julia_box_float64_16886)
>>> referenced 9 more times
```

**Comment by vchuravy** [comment]
Yes but no... This is a tricky design issue/interaction.

I believe this is the same issue as why I want to use the custom method table for all GPU intrinsics and it should be equivalent to adding `precompile()`

Essentially precompilation tracking discards the CI and then uses the MI alone.

**Comment by vchuravy** [comment]
So it would be good to confirm if this is the same as:

https://github.com/JuliaLang/julia/pull/54155

**Comment by maleadt** [comment]
> So it would be good to confirm if this is the same as:
> 
> [JuliaLang/julia#54155](https://github.com/JuliaLang/julia/pull/54155)

Yep, just tested this out, and I can confirm this fixes the precompilation issue.

**Comment by vchuravy** [comment]
Okay... Then we need to decide if this is the right fix... 
I wasn't convinced at the time.

Also just reminded me of https://github.com/JuliaLang/julia/pull/55072#discussion_r1669092995

**Comment by maleadt** [comment]
It's also surprising that this only triggers on Windows, no?

**Comment by vchuravy** [comment]
> It's also surprising that this only triggers on Windows, no?

A little bit...

**Comment by maleadt** [comment]
Workaround: don't build the runtime, so that the simple kernel compiled as part of the precompilation workload doesn't generate GPU-specific code. Seems to keep most of the latency advantage:

```
❯ hyperfine -w 1 " julia --project examples/kernel.jl"
Benchmark 1:  julia --project examples/kernel.jl
  Time (mean ± σ):     977.3 ms ±  12.8 ms    [User: 1042.0 ms, System: 1110.2 ms]
  Range (min … max):   966.3 ms … 1010.9 ms    10 runs
```

**Pull request merged**
