### PR TITLE
Fix context usage and add assertions CI

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Review by vchuravy — APPROVED** [review]
cc: @pchintalapudi

**Comment by maleadt** [comment]
This is looking good. The only problem is that this is a breaking change: GPUCompiler APIs now require a context argument, but importantly, on Julia < 1.9 that needs to be the global unique context. A helper function is provided to look up the global or create a local context, `JuliaContxet()`, but that's a breaking change. We can't leave the context argument away, because on 1.9 it's needed (and we can't create temporary contexts because `emit_llvm` returns LLVM datastructures), but we also can't make it a regular mandatory Context because on 1.8 we can't emit in a specific context...

**Comment by vchuravy** [comment]
So `create_native` can take a null pointer and will then use the global execution context, and there is `jl_get_ee_context()` (for now) that gives you a handle to the global execution context.

I don't know if that's enough to make this non-breaking. `jl_get_ee_context` will disappear hopefully before 1.9 branches, but in the mean time it might help you.

**Comment by maleadt** [comment]
But for 1.9 compatibility callers _need_ to pass a context anyway, so its breaking regardless. The problem is that we can't make it breaking only once, because once we support 1.9 only that global-or-local-JuliaContext will need to become a regular Context. We can't do that now already, because the APIs don't support emitting into a specific context. I also tried to have `irgen` move the data from one context into another (using the serialize-deserialize trick), but that would be costly, and risky since any operation involving Julia proper still assumes a global context (e.g. calling an optimization pass; that would result in segfaults when used with a module that doesn't reside in the global context).

**Comment by vchuravy** [comment]
> (e.g. calling an optimization pass; that would result in segfaults when used with a module that doesn't reside in the global context

At least our optimization passes should already be ignorant of the global context. If not I need to have strong words with my self.

**Comment by maleadt** [comment]
Notes from discussion with @vchuravy:

> the problem is that GPUCompiler APIs now need a context argument. that’s a breaking change, but unavoidable (because some APIs return LLVM datastructures). so we need to add a context argument. on 1.9, that works fine. on older versions, we cannot codegen in a different context, so I work around this by serializing/deserializing right after codegen. everybody is happy. except that this crashes in remapType, but weirdly only on <1.9. however, we can’t realistically backport the fix to all Julia versions. so we’re left with two choices, either do an other serialize/deserialize pair on <1.9 when optimizing to make sure we optimize in the global context. or make it so that we use the global context on <1.9. however, that breaks the API we’ve just started out with: callers now pass a ctx=Context() to GPUCompiler APIs! to solve that, I had introduced JuliaContext(), which on <1.9 returns the global context and on 1.9 a normal ephemeral Context
> so again, we have two choices: either break APIs twice (now add ctx=JuliaContext, later ctx=Context), or break them once but do some horrible hacks in optim because of global context issues

I also added a comment with some details.

**Comment by maleadt** [comment]
Let's merge this and let it brew on master for a while.

**Pull request merged**
