### PR TITLE
Workaround cfunction closures on non-x86

### LINKED ISSUE #187: Aarch64: `Closures are not supported on this platform`
(Issue based on [this slack discussion](https://julialang.slack.com/archives/C689Y34LE/p1620760229042800))

Using the following MWE with the current master of CUDA.jl throws an error `ERROR: cfunction: closures are not supported on this platform`:
```
using Flux
input = rand(Float32, 50,50,1,3) |> gpu
conv = Conv((2,1), 1=>4) |> gpu
conv(input)
```

Additional information:

Full stacktrace:
```julia-repl
ERROR: cfunction: closures are not supported on this platform
Stacktrace:
  [1] compile_method_instance(job::GPUCompiler.CompilerJob, method_instance::Core.MethodInstance)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/eJOtJ/src/jlgen.jl:325
  [2] macro expansion
    @ ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:206 [inlined]
  [3] irgen(job::GPUCompiler.CompilerJob, method_instance::Core.MethodInstance)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/eJOtJ/src/irgen.jl:4
  [4] macro expansion
    @ ~/.julia/packages/GPUCompiler/eJOtJ/src/driver.jl:142 [inlined]
  [5] macro expansion
    @ ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:206 [inlined]
  [6] macro expansion
    @ ~/.julia/packages/GPUCompiler/eJOtJ/src/driver.jl:141 [inlined]
  [7] emit_llvm(job::GPUCompiler.CompilerJob, method_instance::Any, world::UInt64; libraries::Bool, deferred_codegen::Bool, optimize::Bool, only_entry::Bool)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/eJOtJ/src/utils.jl:62
  [8] emit_llvm(job::GPUCompiler.CompilerJob, method_instance::Any, world::UInt64)
    @ GPUCompiler ~/.julia/packages/GPUCompiler/eJOtJ/src/utils.jl:60
  [9] cufunction_compile(job::GPUCompiler.CompilerJob)
    @ CUDA ~/.julia/packages/CUDA/3VnCC/src/compiler/execution.jl:300
 [10] check_cache
    @ ~/.julia/packages/GPUCompiler/eJOtJ/src/cache.jl:47 [inlined]
 [11] cached_compilation
    @ ~/.julia/packages/GPUArrays/4n0iS/src/host/broadcast.jl:57 [inlined]
 [12] cached_compilation(cache::Dict{UInt64, Any}, job::GPUCompiler.CompilerJob{GPUCompiler.PTXCompilerTarget, CUDA.CUDACompilerParams, GPUCompiler.FunctionSpec{GPUArrays.var"#broadcast_kernel#16", Tuple{CUDA.CuKernelContext, CUDA.CuDeviceArray{Float32, 4, 1}, Base.Broadcast.Broadcasted{Nothing, NTuple{4, Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{4}, Nothing, typeof(+), Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceArray{Float32, 4, 1}, NTuple{4, Bool}, NTuple{4, Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceArray{Float32, 4, 1}, NTuple{4, Bool}, NTuple{4, Int64}}}}}}, Int64}}}, compiler::typeof(CUDA.cufunction_compile), linker::typeof(CUDA.cufunction_link))
    @ GPUCompiler ~/.julia/packages/GPUCompiler/eJOtJ/src/cache.jl:0
 [13] cufunction(f::GPUArrays.var"#broadcast_kernel#16", tt::Type{Tuple{CUDA.CuKernelContext, CUDA.CuDeviceArray{Float32, 4, 1}, Base.Broadcast.Broadcasted{Nothing, NTuple{4, Base.OneTo{Int64}}, typeof(identity), Tuple{Base.Broadcast.Broadcasted{CUDA.CuArrayStyle{4}, Nothing, typeof(+), Tuple{Base.Broadcast.Extruded{CUDA.CuDeviceArray{Float32, 4, 1}, NTuple{4, Bool}, NTuple{4, Int64}}, Base.Broadcast.Extruded{CUDA.CuDeviceArray{Float32, 4, 1}, NTuple{4, Bool}, NTuple{4, Int64}}}}}}, Int64}}; name::Nothing, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ CUDA ~/.julia/packages/CUDA/3VnCC/src/compiler/execution.jl:289
 [14] cufunction
    @ ~/.julia/packages/CUDA/3VnCC/src/compiler/execution.jl:283 [inlined]
 [15] macro expansion
    @ ~/.julia/packages/CUDA/3VnCC/src/compiler/execution.jl:102 [inlined]
 [16] #launch_heuristic#286
    @ ~/.julia/packages/CUDA/3VnCC/src/gpuarrays.jl:17 [inlined]
 [17] launch_heuristic
    @ ~/.julia/packages/CUDA/3VnCC/src/gpuarrays.jl:17 [inlined]
 [18] copyto!
    @ ~/.julia/packages/GPUArrays/4n0iS/src/host/broadcast.jl:63 [inlined]
 [19] copyto!
    @ ./broadcast.jl:936 [inlined]
 [20] copy
    @ ~/.julia/packages/GPUArrays/4n0iS/src/host/broadcast.jl:47 [inlined]
 [21] materialize
    @ ./broadcast.jl:883 [inlined]
 [22] (::Conv{2, 4, typeof(identity), CUDA.CuArray{Float32, 4}, CUDA.CuArray{Float32, 1}})(x::CUDA.CuArray{Float32, 4})
    @ Flux ~/.julia/packages/Flux/6o4DQ/src/layers/conv.jl:157
 [23] top-level scope
    @ REPL[62]:1
```

Versioninfo:
```julia-repl
Julia Version 1.6.1
Commit 6aaedecc44 (2021-04-23 05:59 UTC)
Platform Info:
  OS: Linux (aarch64-unknown-linux-gnu)
  CPU: unknown
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, cortex-a57)
Environment:
  JULIA_EDITOR = "/home/sdobber/.vscode-server/bin/cfa2e218100323074ac1948c885448fdf4de2a7f/node"
  JULIA_NUM_THREADS = 
```

CUDA Versioninfo:
```julia-repl
CUDA toolkit 10.2.89, local installation
CUDA driver 10.2.0

Libraries: 
- CUBLAS: 10.2.2
- CURAND: 10.1.2
- CUFFT: 10.1.2
- CUSOLVER: 10.3.0
- CUSPARSE: 10.3.1
- CUPTI: 12.0.0
- NVML: missing
- CUDNN: 8.0.0 (for CUDA 10.2.0)
┌ Warning: Could not find or load CUTENSOR; run with JULIA_DEBUG=CUDA for more details.
└ @ CUDA ~/.julia/packages/CUDA/3VnCC/deps/bindeps.jl:409
- CUTENSOR: missing

Toolchain:
- Julia: 1.6.1
- LLVM: 11.0.1
- PTX ISA support: 3.2, 4.0, 4.1, 4.2, 4.3, 5.0, 6.0, 6.1, 6.3, 6.4, 6.5
- Device support: sm_30, sm_32, sm_35, sm_37, sm_50, sm_52, sm_53, sm_60, sm_61, sm_62, sm_70, sm_72, sm_75

1 device:
  0: NVIDIA Tegra X1 (sm_53, 541.133 MiB / 3.863 GiB available)
```

### PR DESCRIPTION
**Pull request by jpsamaroo**
Not sure if I need a lock, but it sounds like the fact that we've taken the codegen lock means we're already accessing the global exclusively?

Fixes #187

### CODE REVIEW

**Comment by maleadt** [comment]
Did you verify this works? It seems insufficient to me, as it still uses interpolation in the `@cfunction` so would still trigger trampoline codegen. Instead, the non-x86 codepath should use a different `@cfunction` invocation: https://github.com/JuliaGPU/CUDA.jl/blob/c4933bbeefffdf77e1e38c8857decb23b2d2eb52/lib/cudadrv/occupancy.jl#L60-L71

**Comment by jpsamaroo** [comment]
> Did you verify this works?

Yes, I used it to get CUDA.jl 3.2.0 working on MIT's Satori (PPC + CUDA), and I have user code using it successfully. Is the issue that the lookup function should be defined outside of `compile_method_instance`?

> https://github.com/JuliaGPU/CUDA.jl/blob/c4933bbeefffdf77e1e38c8857decb23b2d2eb52/lib/cudadrv/occupancy.jl#L60-L71

That's what I looked at when creating this change :slightly_smiling_face:

**Comment by maleadt** [comment]
> Is the issue that the lookup function should be defined outside of `compile_method_instance`?

No, the issue is that you can't use `$` in `@cfunction` or you trigger a different (incompatible) codegen path. From the docstring:

> Adding a '$' in front of the function argument changes this to instead create a runtime closure over the local variable callable (this is not supported on all architectures).

**Comment by jpsamaroo** [comment]
Oh I see. I'll try it out without the `$` and report back.

**Pull request merged**
