### PR TITLE
Added BPF compiler target

### PR DESCRIPTION
**Pull request by jpsamaroo**

### CODE REVIEW

**Comment by jpsamaroo** [comment]
Note: For whatever reason, LLVM doesn't think it has a target machine supporting the triple `bpf` or `bpf-bpf-bpf`, even though `llc` is able to handle IR with this triple. We use `Sys.MACHINE` temporarily and change it later on, but set the appropriate datalayout.

**Comment by maleadt** [comment]
Tests for nightly?

**Comment by vchuravy** [comment]
Nightly still doesn't have it enabled. Coming soon (tm)

**Comment by jpsamaroo** [comment]
Thanks to Valentin moving us to the bleeding edge of LLVM, the `bpf-bpf-bpf` target works now, and so native output works!

@maleadt I've added some basic tests that confirm that we're getting eBPF assembly output. Let me know if you need more tests than these.

**Comment by jpsamaroo** [comment]
Still todo: move LLVM IR manipulations from BPFnative to GPUCompiler.

**Comment by jpsamaroo** [comment]
Ok, my local dev branch of BPFnative is now passing tests with these changes, so if there are no objections then I'd like to merge this.

**Comment by vchuravy** [comment]
Any ideas why CI is failing?

**Comment by jpsamaroo** [comment]
So that's probably because I guarded `check_method` behind the `validate` flag. I need to do that for BPFnative because operations on BPF maps are represented in LLVM by a `call` on an `i64` value, where the value references which BPF helper function to call (similar to a call to a literal pointer). Without that patch, I get these errors:

```
  InvalidIRError: compiling function mykern(UInt32) resulted in invalid LLVM IR
  Reason: unsupported call through a literal pointer (call to )
```

I suspect the "(call to )" is empty because the validator can't find the name of the function that the literal corresponds to.

Any ideas on how to handle this?

**Comment by maleadt** [comment]
> where the value references which BPF helper function to call

Is it possible to validate these integers? You could allow the validator to accept a list of allowed integers, much like the list of allowed undefined functions right now (which is target-specific too).

**Comment by jpsamaroo** [comment]
They are essentially arbitrary (albeit typically monotonically increasing from 1), since in the case of eBPF interpreters like [ubpf](https://github.com/iovisor/ubpf), you can add functions at whatever integer you want. However, I could easily add a field to `BPFCompilerTarget` that indicates what range or set of integers is considered valid (and probably default it to `1:1000`, which is sufficient for Linux BPF and probably most users of ubpf). `check_ir!` would have to gain a hook to check if certain literal pointers are allowed, though.

**Comment by jpsamaroo** [comment]
Ok I dropped the problematic commit and added support for allowing backends to opt-in to calls to certain pointers.

**Review by maleadt — APPROVED** [review]

**Comment by maleadt** [comment]
CI failure is related.

**Comment by jpsamaroo** [comment]
I'm not really sure what's going on with the macOS failure, especially given that Linux and Windows pass. The changes should only be relevant to other backends if they override `valid_function_pointer`.

**Pull request merged**
