### PR TITLE
SPIR-V target

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
What should we do with backend-specific JLLs? They aren't terribly big, the translator is 1MB while the tools are about 10MB, but they currently are slightly annoying in that they "break" LLVM assert builds (incompatible libLLVMs) and "break" shipping a Manifest (since separate versions are required for each version of Julia).

**Comment by jpsamaroo** [comment]
Could the JLL be installed dynamically during the first creation of a SPIR-V target/job? That might prevent it from interfering with other backends.

**Comment by maleadt** [comment]
> Could the JLL be installed dynamically during the first creation of a SPIR-V target/job? That might prevent it from interfering with other backends.

Xompute nodes typically don't have networking, and doing so outside of Pkg and Project.toml entries breaks semver. Another case for conditional dependencies, I guess...

Maybe lazy artifacts? But then we still have the version dependency /Manifest issue.

**Comment by maleadt** [comment]
Made the JLL dependencies optional, but since they only work on LLVM 8 I ditched the Julia 1.3 compatibility. @jpsamaroo that means there's no GCN CI at all right now, we ought to fix that.

**Pull request merged**
