### PR TITLE
Write the runtime to disk atomically.

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
CUDA.jl failure unrelated.

**Comment by jakebolewski** [comment]
@maleadt can we modify this to `mktemp` in the same parent directory as the runtime file?

```
mktemp(parent=dirname(lib); cleanup=false)
```

that should guarantee that the `mv` is atomic as parent will be on the same filesystem.

**Comment by maleadt** [comment]
Good idea, added that in https://github.com/JuliaGPU/GPUCompiler.jl/pull/83/commits/dbb41ac644e677d6ecae7751bfa27b8df5a5d903

**Comment by maleadt** [comment]
Turns out this isn't atomic after all, because `mv` calls `checkfor_mv_cp_cptree` which does an `rm`, breaking atomicity. I assume this only matters when dealing with directories, not files. Maybe we should just call `Base.rename` which also has a `force=true` kwarg?

**Pull request merged**
