### PR TITLE
Change the GCN triple at the start of optimization.

### PR DESCRIPTION
**Pull request by maleadt**
Otherwise the saved runtime has the wrong one, causing warnings.

### CODE REVIEW

**Comment by maleadt** [comment]
cc @jpsamaroo; AMD CI is broken so I can't verify this, but it seems correct.

**Comment by jpsamaroo** [comment]
@maleadt AMDGPU master/latest release doesn't support 1.6 (intentionally). Can we add 1.7 to CI?

**Comment by maleadt** [comment]
I don't see why not. Probably makes sense to make everything 1.7, but keep one 1.6 job for LTS compatibility.

**Comment by maleadt** [comment]
I don't see why not. Probably makes sense to make everything 1.7, but keep one 1.6 job for LTS compatibility.

**Pull request merged**
