### PR TITLE
Disable GitLab, delete GitLab badge, add Buildkite badge, delete Travis badge, add GitHub Actions badge

### PR DESCRIPTION
**Pull request by DilumAluthge**
1. Delete the `.gitlab-ci.yml` file, which will disable GitLab CI
2. Delete GitLab badge
3. Add Buildkite badge
4. Delete Travis badge
5. Add GitHub Actions badge

### CODE REVIEW

**Comment by maleadt** [comment]
GitLab is still used for AMD GPU CI by @jpsamaroo though... Maybe we ought to port that one to BuildKite too.

**Comment by DilumAluthge** [comment]
> GitLab is still used for AMD GPU CI by @jpsamaroo though... Maybe we ought to port that one to BuildKite too.

Yeah I think it would be good to move everyone to Buildkite and then shut down all of the GitLab JuliaGPU runners. No sense in having to maintain two infrastructures.

We need to migrate this one as well: https://github.com/JuliaGPU/GemmKernels.jl

**Comment by maleadt** [comment]
> We need to migrate this one as well: https://github.com/JuliaGPU/GemmKernels.jl

I'll have a look at that one later today.

**Comment by DilumAluthge** [comment]
> > We need to migrate this one as well: https://github.com/JuliaGPU/GemmKernels.jl
> 
> I'll have a look at that one later today.

Will be easiest if we can move the repo to an org. https://github.com/JuliaGPU/GemmKernels.jl/issues/54

**Comment by maleadt** [comment]
That is the case already.

**Comment by DilumAluthge** [comment]
Nice! I didn't realize.

**Comment by jpsamaroo** [comment]
I'll work on getting AMDGPU CI moved to Buildkite this week. I have a non-systemd server, so I might need to do a bit of fiddling until I can get a working setup together.

**Comment by jpsamaroo** [comment]
Added AMDGPU buildkite CI: https://github.com/JuliaGPU/AMDGPU.jl/pull/80 and https://github.com/JuliaGPU/GPUCompiler.jl/pull/132

**Comment by DilumAluthge** [comment]
@maleadt Good to merge this now?

**Comment by maleadt** [comment]
Yup, thanks!

**Pull request merged**
