### PR TITLE
Don't run global opt when opt disabled

### PR DESCRIPTION
**Pull request by wsmoses**
Required for https://github.com/EnzymeAD/Enzyme.jl/issues/375

### CODE REVIEW

**Comment by maleadt** [comment]
If we make this part of optimization, we should probably move it into the IPO block of the pipeline: https://github.com/JuliaGPU/GPUCompiler.jl/blob/c687cae9510c42cea4c7449731e4a8075f0dc955/src/optim.jl#L247-L262=

There's a reason I didn't do this before though: Because these passes do some 'minimal' IR clean-up that makes it nice to read even when optimization is turned off. I wonder if it would still work without the `global_optimizer!`. What exactly breaks your use case by running the global optimizer?

**Comment by wsmoses** [comment]
So this specifically arises when combining Enzyme with CUDA. In particular CUDA implements math functions like sin in libdevice which CUDA.jl links into the current module (these are marked internal and always online).

Without this change, by the time Enzyme sees the LLVM to differentiate (even with optimization off), all libdevice functions that were not explicitly used in the original kernel are now erased.

Unfortunately as an example, the derivative of sin is cos and as such Enzyme may need some of these libdevice functions even if they weren't used by the original kernel. As such when optimization is disabled the goal of this PR is to preserve such libdevice functions.

**Comment by maleadt** [comment]
> Without this change, by the time Enzyme sees the LLVM to differentiate (even with optimization off), all libdevice functions that were not explicitly used in the original kernel are now erased.

Why do you have Enzyme work with "finalized" IR? Wouldn't it be better to do so earlier, after IR has been generated, but before library linking and optimization?

Anyway, that would probably require some restructuring of the GPUCompiler driver, so it's a much more invasive change. A clean-up flag is easy enough for now.

**Review by maleadt — APPROVED** [review]

**Comment by wsmoses** [comment]
We already disable optimization -- however disabling optimization doesn't doable this.

**Pull request merged**
