### PR TITLE
Allow for deferred codegen in !toplevel

### PR DESCRIPTION
**Pull request by vchuravy**
Fixes https://github.com/EnzymeAD/Enzyme.jl/issues/1173

Need to come up with a standalone test-case.

### CODE REVIEW

**Comment by jgreener64** [comment]
Could this get merged?

**Comment by wsmoses** [comment]
@vchuravy gentle bump

**Comment by vchuravy** [comment]
I tried reproducing the Enzyme MWE with `examples/jit.jl` but the stars didn't align.

@maleadt do you recall why you limited this to `toplevel` originally? I assume because it wouldn't make sense for device side launched kernels.

**Review by maleadt — CHANGES_REQUESTED** [review]
The reasoning is that deferred functions called from the entrypoint (which is what the compiler driver is architected around) can be discovered recursively without having to expand them during deferred compilation. I guess that this doesn't hold with Enzyme because the deferred compilation jobs aren't called by the main entrypoint? To support this, the compiler driver will need to be changed. For example, if you simply let them expand from within a deferred context as proposed here, the `jobs` variable at top level won't list all compilation jobs, and the post-processing that happens at top level won't be executing on all functions.

**Comment by maleadt** [comment]
Yes, but that doesn't correctly populate the `jobs` variable that's used at top level: https://github.com/JuliaGPU/GPUCompiler.jl/blob/288b613bc1b7e1c1d0ebd4274b5784d5d2ece86d/src/driver.jl#L423-L435
We could work around this by passing `jobs` to the inner deferred codegen generators, but that's a hack. Essentially the current system relies on a compilation job having a single point of entry, even into deferred jobs.

**Comment by vchuravy** [comment]
Hm I am a bit confused how 

https://github.com/JuliaGPU/CUDA.jl/blob/c2d444b0f5a76f92c5ba6bc1534a53319218b563/test/core/execution.jl#L974-L1002

works.  I just pushed a commit that returns the job variable from the `!toplevel` compilation.

**Comment by maleadt** [comment]
> Hm I am a bit confused how
> 
> https://github.com/JuliaGPU/CUDA.jl/blob/c2d444b0f5a76f92c5ba6bc1534a53319218b563/test/core/execution.jl#L974-L1002

We probably don't really rely on the `finish_ir` phase right now.

I'm not particularly happy with threading yet more state through, but if you need this... The compiler driver should be reworked to support compiling multiple translation units without relying on a single entry-point.

**Comment by vchuravy** [comment]
Yeah I can try to improve this while working on #582

**Comment by maleadt** [comment]
CUDA.jl CI failure looks related.

**Comment by vchuravy** [comment]
Ah I see for https://github.com/JuliaGPU/CUDA.jl/blob/c2d444b0f5a76f92c5ba6bc1534a53319218b563/test/core/execution.jl#L974-L975

We have an infinite loop since we don't pass through the list of already codegen'd functions. So we recurse into the original top-level and carry on from there.

**Pull request closed without merging**
