### PR TITLE
CI: Add Julia 1.7 jobs

### PR DESCRIPTION
**Pull request by jpsamaroo**
Extend AMDGPU job timeout to 3 hours
Make AMDGPU job success mandatory

### CODE REVIEW

**Comment by maleadt** [comment]
Yeah the oneAPI machine at MIT has been down for weeks... (cc @vchuravy)
I'm hoping to replace it with one I manage, but there's bugs in the Intel compiler on that platform...

**Comment by maleadt** [comment]
oneAPI bot is back, so its 1.7 CI job can be re-enabled.

**Comment by vchuravy** [comment]
@jpsamaroo Can you revert 672edb5

**Comment by maleadt** [comment]
Maybe rebase for Enzyme?

**Comment by maleadt** [comment]
This seems stale.

**Pull request closed without merging**
