### PR TITLE
Bump minimum Julia requirement to Julia 1.8

### PR DESCRIPTION
**Pull request by maleadt**
Maintaining 1.6 compatibility was becoming tedious, and we had two back-ends that required 1.8 already. With 1.10 presumably becoming the new LTS, it seems reasonable to bump the minimum requirement.

cc @vchuravy @jpsamaroo

### CODE REVIEW

**Comment by vchuravy** [comment]
cc: @wsmoses since this will impact Enzyme as well.

**Comment by wsmoses** [comment]
Is it possible to wait to merge this until a few weeks after 1.10 is released and formally marked as the new LTS?

I want to make sure we shake out any bugs caused by folks deploying 1.10 before we drop the old LTS.

**Comment by maleadt** [comment]
I don't think it will be formally marked LTS until we have 1.11, or at least with 1.6 it took a while. So I'd rather not postpone it that much. Instead we can just maintain a backports branch for packages that do want to keep working with 1.6 for now.

**Comment by maleadt** [comment]
Discussed this on the GPU dev call, and it seems to make sense to move the minimum requirement to 1.8 (for one, the new scoped values support will also require it). We'll maintain a backports branch of 0.22, i.e. the current GPUCompiler version, until the new LTS has been announced some more.

**Pull request merged**
