### PR TITLE
Fix issue with `__init__` when built in sysimg

### PR DESCRIPTION
**Pull request by sjkelly**
see: https://github.com/JuliaLang/PackageCompiler.jl/issues/896

### CODE REVIEW

**Comment by maleadt** [comment]
Hmm, that's not great, because it will mean that if you build multiple sysimages with different GPUCompiler.jl versions, the compiled artifacts will alias. In the case of PackageCompiler.jl apps, I assume the depot will be unique to the package, with with regular sysimages this can definitely happen.

@KristofferC Is there a way to query the version of a package (i.e. `Base.pkgversion`) that's been built in the system image?

**Comment by sjkelly** [comment]
How about we move the `pkgversion` call outside of the `__init__` so it is compiled-in.

**Comment by KristofferC** [comment]
`pkgversion` just seem badly implemented... The information should be there:

```
julia> [(k.name => v.version) for (k,v) in Base.pkgorigins]
37-element Vector{Pair{String}}:
   "LibSSH2_jll" => v"1.11.0+1"
  "OpenBLAS_jll" => v"0.3.23+4"
   "nghttp2_jll" => v"1.52.0+1"
 "Serialization" => nothing
   "LibGit2_jll" => v"1.6.4+0"
...
```

**Comment by KristofferC** [comment]
But I am still a bit confused. Why would the version in `__init__` be different from that during precompilation?

**Comment by maleadt** [comment]
> How about we move the `pkgversion` call outside of the `__init__` so it is compiled-in.

That sounds reasonable, but doing during precompilation sounds like there may be corner cases too. I'll have a closer look tomorrow, maybe we should just look in `Base.pkgorigins` as Kristoffer shows above until `pkgversion` is fixed in Base.

**Comment by maleadt** [comment]
I cannot reproduce the underlying issue in isolation.

```julia
❯ jl --project
(test) pkg> add Example PackageCompiler
julia> using Example, PackageCompiler
julia> PackageCompiler.create_sysimage(["Example"]; sysimage_path="example-sysimage.so")

❯ jl --project -e 'using Example; @show pkgversion(Example)'
pkgversion(Example) = v"0.5.3"

❯ jl --sysimage=example-sysimage.so --project -e 'using Example; @show pkgversion(Example)'
pkgversion(Example) = v"0.5.3"
```

Or even using GPUCompiler:

```julia
julia> PackageCompiler.create_sysimage(["GPUCompiler"]; sysimage_path="gpucompiler-sysimage.so")

❯ jl --sysimage=gpucompiler-sysimage.so -e 'using GPUCompiler; @show GPUCompiler.compile_cache'
GPUCompiler.compile_cache = "/home/tim/.julia/scratchspaces/61eb1bfa-7361-4325-ad38-22787b887f55/compiled/v1.10/v0.26"
```

**Comment by KristofferC** [comment]
How about if you delete the `.julia/packages/GPUCompiler` folder?

**Comment by KristofferC** [comment]
Okay but how. Looking at

https://github.com/JuliaLang/julia/blob/8791d54d142cb27690e2e7d74b1e01733f7d9a3a/base/loading.jl#L560

and

https://github.com/JuliaLang/julia/blob/8791d54d142cb27690e2e7d74b1e01733f7d9a3a/base/loading.jl#L529

if the project file doesn't exist it seems it should return `nothing`, or?

Why does calling `pkgversion` outside of `__init__` not work? It should give the same version as that in `__init__` or what am I misunderstanding? How can the version change between precompilation time and runtime?

**Comment by maleadt** [comment]
> Why does calling `pkgversion` outside of `__init__` not work? It should give the same version as that in `__init__` or what am I misunderstanding? How can the version change between precompilation time and runtime?

It shouldn't. I'm wasn't suggesting the proposed workaround of putting the call to `Base.pkgversion` outside of `__init__` is wrong or anything, I just failed to observe the failure with `Base.pkgversion` in combination with packages embedded in a system image in the first place.

I was just trying to validate the 'workaround', but if @sjkelly has observed that this fixes his issue, this is fine for me.

**Pull request merged**
